exp_name: wavlm_Nes2Net_NoAug_seed42
output_dir: ./outputs/batch1/
seed: 42
data:
  sampling_rate: 16000
  label_map:
    bonafide: 1
    spoof: 0
  train:
    dataset_type: StandardDataset
    parquet_files:
    - /netscratch/yelkheir/DeepFense/DeepFense/deepfense/config/parquets/asvspoof19_train.parquet
    dataset_names:
    - ASVSpoof19_Train
    batch_size: 32
    shuffle: true
    num_workers: 4
    base_transform:
    - type: pad
      max_len: 64000
      random_pad: true
      pad_type: repeat
    augment_transform: []
  val:
    dataset_type: StandardDataset
    parquet_files:
    - /netscratch/yelkheir/DeepFense/DeepFense/deepfense/config/parquets/asvspoof19_val.parquet
    dataset_names:
    - ASVSpoof19_Val
    batch_size: 32
    shuffle: false
    num_workers: 4
    base_transform:
    - type: pad
      max_len: 64000
      pad_type: repeat
model:
  type: StandardDetector
  frontend:
    type: wavlm
    args:
      ckpt_path: /netscratch/yelkheir/ssl_models/WavLM-Large.pt
      freeze: false
      source: unil
  backend:
    type: Nes2Net
  loss:
  - type: CrossEntropy
    embedding_dim: 1024
    n_classes: 2
    weight: 1.0
training:
  trainer: StandardTrainer
  epochs: 100
  early_stopping_patience: 7
  optimizer:
    type: adam
    lr: 1.0e-06
  metrics:
    ACC: {}
    EER: {}
  eval_every_epochs: 1
  device: cuda
  output_dir: ./outputs/batch1/wavlm_Nes2Net_NoAug_seed42_20260129_145324
